name: ExampleProject
description: An example project for spigot 1.8.9
main: com.example.exampleproject.ExampleProject
version: 1.0.0
api-version: 1.13
author: Your_Name
website: Website-Feel-Free-To-Remove
depend: []
softdepend: []
commands:
  exampleproject:
    description: A command.
    aliases: []
    usage: /exampleproject